/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProjectStageService } from "../projectStage.service";
import { ProjectStageCreateInput } from "./ProjectStageCreateInput";
import { ProjectStage } from "./ProjectStage";
import { ProjectStageFindManyArgs } from "./ProjectStageFindManyArgs";
import { ProjectStageWhereUniqueInput } from "./ProjectStageWhereUniqueInput";
import { ProjectStageUpdateInput } from "./ProjectStageUpdateInput";
import { ContractorAssignmentFindManyArgs } from "../../contractorAssignment/base/ContractorAssignmentFindManyArgs";
import { ContractorAssignment } from "../../contractorAssignment/base/ContractorAssignment";
import { ContractorAssignmentWhereUniqueInput } from "../../contractorAssignment/base/ContractorAssignmentWhereUniqueInput";
import { PositionRequirementFindManyArgs } from "../../positionRequirement/base/PositionRequirementFindManyArgs";
import { PositionRequirement } from "../../positionRequirement/base/PositionRequirement";
import { PositionRequirementWhereUniqueInput } from "../../positionRequirement/base/PositionRequirementWhereUniqueInput";

export class ProjectStageControllerBase {
  constructor(protected readonly service: ProjectStageService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProjectStage })
  async createProjectStage(
    @common.Body() data: ProjectStageCreateInput
  ): Promise<ProjectStage> {
    return await this.service.createProjectStage({
      data: {
        ...data,

        project: data.project
          ? {
              connect: data.project,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        stageNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ProjectStage] })
  @ApiNestedQuery(ProjectStageFindManyArgs)
  async projectStages(@common.Req() request: Request): Promise<ProjectStage[]> {
    const args = plainToClass(ProjectStageFindManyArgs, request.query);
    return this.service.projectStages({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        stageNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProjectStage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async projectStage(
    @common.Param() params: ProjectStageWhereUniqueInput
  ): Promise<ProjectStage | null> {
    const result = await this.service.projectStage({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        stageNumber: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProjectStage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProjectStage(
    @common.Param() params: ProjectStageWhereUniqueInput,
    @common.Body() data: ProjectStageUpdateInput
  ): Promise<ProjectStage | null> {
    try {
      return await this.service.updateProjectStage({
        where: params,
        data: {
          ...data,

          project: data.project
            ? {
                connect: data.project,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          name: true,

          project: {
            select: {
              id: true,
            },
          },

          stageNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProjectStage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProjectStage(
    @common.Param() params: ProjectStageWhereUniqueInput
  ): Promise<ProjectStage | null> {
    try {
      return await this.service.deleteProjectStage({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,

          project: {
            select: {
              id: true,
            },
          },

          stageNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/contractorAssignments")
  @ApiNestedQuery(ContractorAssignmentFindManyArgs)
  async findContractorAssignments(
    @common.Req() request: Request,
    @common.Param() params: ProjectStageWhereUniqueInput
  ): Promise<ContractorAssignment[]> {
    const query = plainToClass(ContractorAssignmentFindManyArgs, request.query);
    const results = await this.service.findContractorAssignments(params.id, {
      ...query,
      select: {
        contractor: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        endDate: true,
        id: true,
        loading: true,

        projectStage: {
          select: {
            id: true,
          },
        },

        startDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/contractorAssignments")
  async connectContractorAssignments(
    @common.Param() params: ProjectStageWhereUniqueInput,
    @common.Body() body: ContractorAssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      contractorAssignments: {
        connect: body,
      },
    };
    await this.service.updateProjectStage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/contractorAssignments")
  async updateContractorAssignments(
    @common.Param() params: ProjectStageWhereUniqueInput,
    @common.Body() body: ContractorAssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      contractorAssignments: {
        set: body,
      },
    };
    await this.service.updateProjectStage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/contractorAssignments")
  async disconnectContractorAssignments(
    @common.Param() params: ProjectStageWhereUniqueInput,
    @common.Body() body: ContractorAssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      contractorAssignments: {
        disconnect: body,
      },
    };
    await this.service.updateProjectStage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/positionRequirements")
  @ApiNestedQuery(PositionRequirementFindManyArgs)
  async findPositionRequirements(
    @common.Req() request: Request,
    @common.Param() params: ProjectStageWhereUniqueInput
  ): Promise<PositionRequirement[]> {
    const query = plainToClass(PositionRequirementFindManyArgs, request.query);
    const results = await this.service.findPositionRequirements(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        jobTitle: true,

        projectStage: {
          select: {
            id: true,
          },
        },

        quantity: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/positionRequirements")
  async connectPositionRequirements(
    @common.Param() params: ProjectStageWhereUniqueInput,
    @common.Body() body: PositionRequirementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      positionRequirements: {
        connect: body,
      },
    };
    await this.service.updateProjectStage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/positionRequirements")
  async updatePositionRequirements(
    @common.Param() params: ProjectStageWhereUniqueInput,
    @common.Body() body: PositionRequirementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      positionRequirements: {
        set: body,
      },
    };
    await this.service.updateProjectStage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/positionRequirements")
  async disconnectPositionRequirements(
    @common.Param() params: ProjectStageWhereUniqueInput,
    @common.Body() body: PositionRequirementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      positionRequirements: {
        disconnect: body,
      },
    };
    await this.service.updateProjectStage({
      where: params,
      data,
      select: { id: true },
    });
  }
}
