/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProjectService } from "../project.service";
import { ProjectCreateInput } from "./ProjectCreateInput";
import { Project } from "./Project";
import { ProjectFindManyArgs } from "./ProjectFindManyArgs";
import { ProjectWhereUniqueInput } from "./ProjectWhereUniqueInput";
import { ProjectUpdateInput } from "./ProjectUpdateInput";
import { EmployeeAssignmentFindManyArgs } from "../../employeeAssignment/base/EmployeeAssignmentFindManyArgs";
import { EmployeeAssignment } from "../../employeeAssignment/base/EmployeeAssignment";
import { EmployeeAssignmentWhereUniqueInput } from "../../employeeAssignment/base/EmployeeAssignmentWhereUniqueInput";
import { ProjectStageFindManyArgs } from "../../projectStage/base/ProjectStageFindManyArgs";
import { ProjectStage } from "../../projectStage/base/ProjectStage";
import { ProjectStageWhereUniqueInput } from "../../projectStage/base/ProjectStageWhereUniqueInput";

export class ProjectControllerBase {
  constructor(protected readonly service: ProjectService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Project })
  async createProject(
    @common.Body() data: ProjectCreateInput
  ): Promise<Project> {
    return await this.service.createProject({
      data: data,
      select: {
        country: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Project] })
  @ApiNestedQuery(ProjectFindManyArgs)
  async projects(@common.Req() request: Request): Promise<Project[]> {
    const args = plainToClass(ProjectFindManyArgs, request.query);
    return this.service.projects({
      ...args,
      select: {
        country: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Project })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async project(
    @common.Param() params: ProjectWhereUniqueInput
  ): Promise<Project | null> {
    const result = await this.service.project({
      where: params,
      select: {
        country: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Project })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProject(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() data: ProjectUpdateInput
  ): Promise<Project | null> {
    try {
      return await this.service.updateProject({
        where: params,
        data: data,
        select: {
          country: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Project })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProject(
    @common.Param() params: ProjectWhereUniqueInput
  ): Promise<Project | null> {
    try {
      return await this.service.deleteProject({
        where: params,
        select: {
          country: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/employeeAssignments")
  @ApiNestedQuery(EmployeeAssignmentFindManyArgs)
  async findEmployeeAssignments(
    @common.Req() request: Request,
    @common.Param() params: ProjectWhereUniqueInput
  ): Promise<EmployeeAssignment[]> {
    const query = plainToClass(EmployeeAssignmentFindManyArgs, request.query);
    const results = await this.service.findEmployeeAssignments(params.id, {
      ...query,
      select: {
        createdAt: true,

        employee: {
          select: {
            id: true,
          },
        },

        endDate: true,
        id: true,
        loading: true,

        positionRequirement: {
          select: {
            id: true,
          },
        },

        project: {
          select: {
            id: true,
          },
        },

        startDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/employeeAssignments")
  async connectEmployeeAssignments(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: EmployeeAssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      employeeAssignments: {
        connect: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/employeeAssignments")
  async updateEmployeeAssignments(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: EmployeeAssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      employeeAssignments: {
        set: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/employeeAssignments")
  async disconnectEmployeeAssignments(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: EmployeeAssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      employeeAssignments: {
        disconnect: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/projectStages")
  @ApiNestedQuery(ProjectStageFindManyArgs)
  async findProjectStages(
    @common.Req() request: Request,
    @common.Param() params: ProjectWhereUniqueInput
  ): Promise<ProjectStage[]> {
    const query = plainToClass(ProjectStageFindManyArgs, request.query);
    const results = await this.service.findProjectStages(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        stageNumber: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/projectStages")
  async connectProjectStages(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: ProjectStageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectStages: {
        connect: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/projectStages")
  async updateProjectStages(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: ProjectStageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectStages: {
        set: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/projectStages")
  async disconnectProjectStages(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: ProjectStageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectStages: {
        disconnect: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }
}
